/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.ispirt.pushpaka.flightauthorisation.api;

import in.ispirt.pushpaka.models.AirspaceUsageToken;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import javax.annotation.Generated;
import javax.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

@Generated(
  value = "org.openapitools.codegen.languages.SpringCodegen",
  date = "2023-09-07T22:13:29.143496+05:30[Asia/Kolkata]"
)
@Validated
@Tag(name = "airspaceUsageTokens", description = "AirspaceUsageTokens")
public interface AirspaceUsageTokenApi {
  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  /**
   * POST /airspaceUsageToken : Add a new AirspaceUsageToken to the store
   * Add a new AirspaceUsageToken to the store
   *
   * @param AirspaceUsageToken Create a new AirspaceUsageToken in the store (required)
   * @return Successful operation (status code 200)
   *         or Invalid input (status code 405)
   */
  @Operation(
    operationId = "addAirspaceUsageToken",
    summary = "Add a new AirspaceUsageToken to the store",
    description = "Add a new AirspaceUsageToken to the store",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = AirspaceUsageToken.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/airspaceUsageToken",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<AirspaceUsageToken> addAirspaceUsageToken(
    @Parameter(
      name = "AirspaceUsageToken",
      description = "Create a new AirspaceUsageToken in the store",
      required = true
    ) @Valid @RequestBody AirspaceUsageToken aut
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * DELETE /airspaceUsageToken/{AirspaceUsageTokenId} : Deletes a aut
   *
   *
   * @param AirspaceUsageTokenId AirspaceUsageToken id to delete (required)
   * @return Invalid AirspaceUsageToken value (status code 400)
   */
  @Operation(
    operationId = "deleteAirspaceUsageToken",
    summary = "Deletes a AirspaceUsageToken",
    description = "",
    responses = {
      @ApiResponse(responseCode = "400", description = "Invalid AirspaceUsageToken value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.DELETE,
    value = "/airspaceUsageToken/{AirspaceUsageTokenId}"
  )
  default ResponseEntity<Void> deleteAirspaceUsageToken(
    @Parameter(
      name = "AirspaceUsageTokenId",
      description = "AirspaceUsageToken id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("AirspaceUsageTokenId") UUID AirspaceUsageTokenId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * GET /airspaceUsageToken/find : Finds AirspaceUsageTokens
   *
   * @return successful operation (status code 200)
   *         or Invalid value (status code 400)
   */
  @Operation(
    operationId = "findAirspaceUsageTokens",
    summary = "Finds AirspaceUsageTokens",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            array = @ArraySchema(
              schema = @Schema(implementation = AirspaceUsageToken.class)
            )
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/airspaceUsageToken/find",
    produces = { "application/json" }
  )
  default ResponseEntity<List<AirspaceUsageToken>> findAirspaceUsageTokens() {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * GET /airspaceUsageToken/{AirspaceUsageTokenId} : Find AirspaceUsageToken by ID
   * Returns a single AirspaceUsageToken
   *
   * @param AirspaceUsageTokenId ID of AirspaceUsageToken to return (required)
   * @return successful operation (status code 200)
   *         or Invalid ID supplied (status code 400)
   *         or AirspaceUsageToken not found (status code 404)
   */
  @Operation(
    operationId = "getAirspaceUsageTokenById",
    summary = "Find AirspaceUsageToken by ID",
    description = "Returns a single AirspaceUsageToken",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = AirspaceUsageToken.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "AirspaceUsageToken not found")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/airspaceUsageToken/{AirspaceUsageTokenId}",
    produces = { "application/json" }
  )
  default ResponseEntity<AirspaceUsageToken> getAirspaceUsageTokenById(
    @Parameter(
      name = "AirspaceUsageTokenId",
      description = "ID of AirspaceUsageToken to return",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("AirspaceUsageTokenId") UUID AirspaceUsageTokenId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * PUT /airspaceUsageToken/{AirspaceUsageTokenId} : Updates a AirspaceUsageToken in the store with form data
   *
   *
   * @param AirspaceUsageTokenId ID of AirspaceUsageToken that needs to be updated (required)
   * @param name Name of AirspaceUsageToken that needs to be updated (optional)
   * @param status Status of AirspaceUsageToken that needs to be updated (optional)
   * @return Invalid input (status code 405)
   */
  @Operation(
    operationId = "updateAirspaceUsageToken",
    summary = "Updates a AirspaceUsageToken in the store",
    description = "",
    responses = { @ApiResponse(responseCode = "405", description = "Invalid input") },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.PUT,
    value = "/airspaceUsageToken/{AirspaceUsageTokenId}"
  )
  default ResponseEntity<AirspaceUsageToken> updateAirspaceUsageToken(
    @Parameter(
      name = "AirspaceUsageTokenId",
      description = "ID of AirspaceUsageToken that needs to be updated",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("AirspaceUsageTokenId") UUID AirspaceUsageTokenId,
    @Parameter(
      name = "AirspaceUsageToken",
      description = "Create a new AirspaceUsageToken in the store",
      required = true
    ) @Valid @RequestBody AirspaceUsageToken AirspaceUsageToken
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
