openapi: 3.0.1
info:
  title: Pushpaka Registry
  description: "This is a sample UasType Store Server based on the OpenAPI 3.0 specification.\
    \  You can find out more about Swagger at [http://swagger.io](http://swagger.io).\
    \ In the third iteration of the uasType store, we've switched to the design first\
    \ approach! You can now help us improve the API whether it's by making changes\
    \ to the definition itself or to the code. That way, with time, we can improve\
    \ the API in general, and expose some of the new features in OAS3.  Some useful\
    \ links: - [The UasType Store repository](https://github.com/swagger-api/swagger-petstore)\
    \ - [The source API definition for the UasType Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)"
  termsOfService: http://swagger.io/terms/
  contact:
    email: sayandeep@ispirt.in
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.17
servers:
- url: http://localhost:8083/
tags:
- name: flightPlans
  description: flightPlans
paths:
  /api/v1/FlightPlan/{FlightPlanId}:
    get:
      tags:
      - flightPlans
      - FlightPlan
      summary: Find FlightPlan by ID
      description: Returns a single FlightPlan
      operationId: getFlightPlanById
      parameters:
      - name: FlightPlanId
        in: path
        description: ID of FlightPlan to return
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightPlan'
        "400":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightPlan'
        "404":
          description: FlightPlan not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightPlan'
      security:
      - flightauthorisation_auth:
        - write:flightPlans
        - read:flightPlans
    put:
      tags:
      - flightPlans
      - FlightPlan
      summary: Updates a FlightPlan in the store
      operationId: updateFlightPlan
      parameters:
      - name: FlightPlanId
        in: path
        description: ID of FlightPlan that needs to be updated
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightPlan'
        required: true
      responses:
        "405":
          description: Invalid input
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FlightPlan'
      security:
      - flightauthorisation_auth:
        - write:flightPlans
        - read:flightPlans
    delete:
      tags:
      - flightPlans
      - FlightPlan
      summary: Deletes a FlightPlan
      operationId: deleteFlightPlan
      parameters:
      - name: FlightPlanId
        in: path
        description: FlightPlan id to delete
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "400":
          description: Invalid FlightPlan value
      security:
      - flightauthorisation_auth:
        - write:flightPlans
        - read:flightPlans
  /api/v1/FlightPlan:
    post:
      tags:
      - flightPlans
      - FlightPlan
      summary: Add a new FlightPlan to the store
      description: Add a new FlightPlan to the store
      operationId: addFlightPlan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightPlan'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightPlan'
        "405":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightPlan'
      security:
      - flightauthorisation_auth:
        - write:flightPlans
        - read:flightPlans
  /api/v1/FlightPlan/find:
    get:
      tags:
      - flightPlans
      - FlightPlan
      summary: Finds flightPlans
      operationId: findflightPlans
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FlightPlan'
        "400":
          description: Invalid value
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FlightPlan'
      security:
      - flightauthorisation_auth:
        - write:flightPlans
        - read:flightPlans
components:
  schemas:
    FlightPlan:
      required:
      - id
      type: object
      properties:
        id:
          type: string
          format: uuid
  securitySchemes:
    registry_auth:
      type: oauth2
    api_key:
      type: apiKey
      name: api_key
      in: header
