---
# This runs SpiceDB, using Postgres as the storage engine. SpiceDB will not have
# any schema written to it.
#
# Once the database service is running, the migrate service executes, running
# "spicedb migrate head" to migrate Postgres to the most current revision. After
# Postgres is migrated, the migrate service will stop.
#
# SpiceDB settings:
#   pre-shared key: foobar
#   dashboard address: http://localhost:8080
#   metrics address: http://localhost:9090
#   grpc address: http://localhost:50051
#
# Postgres settings:
#   user: postgres
#   password: secret
#   port: 5432

version: "3"

services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    # container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak
    command: start-dev

  spicedb:
    image: "authzed/spicedb"
    command: "serve"
    restart: "always"
    ports:
      - "8081:8080"
      - "9090:9090"
      - "50051:50051"
    environment:
      - "SPICEDB_GRPC_PRESHARED_KEY=${SPICEDB_GRPC_PRESHARED_KEY}"
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/spicedb?sslmode=disable"
    depends_on:
      - "migrate"

  migrate:
    image: "authzed/spicedb"
    command: "migrate head"
    restart: "on-failure"
    environment:
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/spicedb?sslmode=disable"
    depends_on:
      - "database"

  database:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DBNAME}"

  crdb:
    image: cockroachdb/cockroach:v19.2.2
    ports:
      - "26257:26257"
      - "8082:8080"
    command: start-single-node --insecure

networks:
  local-keycloak:

