/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.ispirt.pushpaka.registry.api;

import in.ispirt.pushpaka.models.CivilAviationAuthority;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

@Generated(
  value = "org.openapitools.codegen.languages.SpringCodegen",
  date = "2023-09-07T22:13:29.143496+05:30[Asia/Kolkata]"
)
@Validated
@Tag(name = "civilAviationAuthorities", description = "CivilAviationAuthorities")
public interface CivilAviationAuthorityApi {
  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  @Operation(
    operationId = "addCivilAviationAuthority",
    summary = "Add a new civilAviationAuthority to the store",
    description = "Add a new civilAviationAuthority to the store",
    tags = { "civilAviationAuthority" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = CivilAviationAuthority.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/civilAviationAuthority",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<CivilAviationAuthority> addCivilAviationAuthority(
    @Parameter(
      name = "CivilAviationAuthority",
      description = "Create a new civilAviationAuthority in the store",
      required = true
    ) @Valid @RequestBody CivilAviationAuthority civilAviationAuthority
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "deleteCivilAviationAuthority",
    summary = "Deletes a civilAviationAuthority",
    description = "",
    tags = { "civilAviationAuthority" },
    responses = {
      @ApiResponse(
        responseCode = "400",
        description = "Invalid civilAviationAuthority value"
      )
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.DELETE,
    value = "/civilAviationAuthority/{civilAviationAuthorityId}"
  )
  default ResponseEntity<Void> deleteCivilAviationAuthority(
    @Parameter(
      name = "civilAviationAuthorityId",
      description = "CivilAviationAuthority id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("civilAviationAuthorityId") UUID civilAviationAuthorityId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "findCivilAviationAuthorities",
    summary = "Finds CivilAviationAuthorities",
    tags = { "civilAviationAuthority" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            array = @ArraySchema(
              schema = @Schema(implementation = CivilAviationAuthority.class)
            )
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/civilAviationAuthority/find",
    produces = { "application/json" }
  )
  default ResponseEntity<List<CivilAviationAuthority>> findCivilAviationAuthorities() {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "getCivilAviationAuthorityById",
    summary = "Find civilAviationAuthority by ID",
    description = "Returns a single civilAviationAuthority",
    tags = { "civilAviationAuthority" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = CivilAviationAuthority.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "CivilAviationAuthority not found")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/civilAviationAuthority/{civilAviationAuthorityId}",
    produces = { "application/json" }
  )
  default ResponseEntity<CivilAviationAuthority> getCivilAviationAuthorityById(
    @Parameter(
      name = "civilAviationAuthorityId",
      description = "ID of civilAviationAuthority to return",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("civilAviationAuthorityId") UUID civilAviationAuthorityId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "updateCivilAviationAuthority",
    summary = "Updates a civilAviationAuthority in the store",
    description = "",
    tags = { "civilAviationAuthority" },
    responses = { @ApiResponse(responseCode = "405", description = "Invalid input") },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.PUT,
    value = "/civilAviationAuthority/{civilAviationAuthorityId}"
  )
  default ResponseEntity<CivilAviationAuthority> updateCivilAviationAuthority(
    @Parameter(
      name = "civilAviationAuthorityId",
      description = "ID of civilAviationAuthority that needs to be updated",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("civilAviationAuthorityId") UUID civilAviationAuthorityId,
    @Parameter(
      name = "CivilAviationAuthority",
      description = "Create a new civilAviationAuthority in the store",
      required = true
    ) @Valid @RequestBody CivilAviationAuthority civilAviationAuthority
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
