/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.ispirt.pushpaka.registry.api;

import in.ispirt.pushpaka.models.DigitalSkyServiceProvider;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

@Generated(
  value = "org.openapitools.codegen.languages.SpringCodegen",
  date = "2023-09-07T22:13:29.143496+05:30[Asia/Kolkata]"
)
@Validated
@Tag(name = "digitalSkyServiceProviders", description = "DigitalSkyServiceProviders")
public interface DigitalSkyServiceProviderApi {
  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  @Operation(
    operationId = "addDigitalSkyServiceProvider",
    summary = "Add a new digitalSkyServiceProvider to the store",
    description = "Add a new digitalSkyServiceProvider to the store",
    tags = { "digitalSkyServiceProvider" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = DigitalSkyServiceProvider.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/digitalSkyServiceProvider",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<DigitalSkyServiceProvider> addDigitalSkyServiceProvider(
    @Parameter(
      name = "DigitalSkyServiceProvider",
      description = "Create a new digitalSkyServiceProvider in the store",
      required = true
    ) @Valid @RequestBody DigitalSkyServiceProvider digitalSkyServiceProvider
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "deleteDigitalSkyServiceProvider",
    summary = "Deletes a digitalSkyServiceProvider",
    description = "",
    tags = { "digitalSkyServiceProvider" },
    responses = {
      @ApiResponse(
        responseCode = "400",
        description = "Invalid digitalSkyServiceProvider value"
      )
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.DELETE,
    value = "/digitalSkyServiceProvider/{digitalSkyServiceProviderId}"
  )
  default ResponseEntity<Void> deleteDigitalSkyServiceProvider(
    @Parameter(
      name = "digitalSkyServiceProviderId",
      description = "DigitalSkyServiceProvider id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("digitalSkyServiceProviderId") UUID digitalSkyServiceProviderId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "findDigitalSkyServiceProviders",
    summary = "Finds DigitalSkyServiceProviders",
    tags = { "digitalSkyServiceProvider" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            array = @ArraySchema(
              schema = @Schema(implementation = DigitalSkyServiceProvider.class)
            )
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/digitalSkyServiceProvider/find",
    produces = { "application/json" }
  )
  default ResponseEntity<List<DigitalSkyServiceProvider>> findDigitalSkyServiceProviders() {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "getDigitalSkyServiceProviderById",
    summary = "Find digitalSkyServiceProvider by ID",
    description = "Returns a single digitalSkyServiceProvider",
    tags = { "digitalSkyServiceProvider" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = DigitalSkyServiceProvider.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(
        responseCode = "404",
        description = "DigitalSkyServiceProvider not found"
      )
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/digitalSkyServiceProvider/{digitalSkyServiceProviderId}",
    produces = { "application/json" }
  )
  default ResponseEntity<DigitalSkyServiceProvider> getDigitalSkyServiceProviderById(
    @Parameter(
      name = "digitalSkyServiceProviderId",
      description = "ID of digitalSkyServiceProvider to return",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("digitalSkyServiceProviderId") UUID digitalSkyServiceProviderId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "updateDigitalSkyServiceProvider",
    summary = "Updates a digitalSkyServiceProvider in the store",
    description = "",
    tags = { "digitalSkyServiceProvider" },
    responses = { @ApiResponse(responseCode = "405", description = "Invalid input") },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.PUT,
    value = "/digitalSkyServiceProvider/{digitalSkyServiceProviderId}"
  )
  default ResponseEntity<DigitalSkyServiceProvider> updateDigitalSkyServiceProvider(
    @Parameter(
      name = "digitalSkyServiceProviderId",
      description = "ID of digitalSkyServiceProvider that needs to be updated",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("digitalSkyServiceProviderId") UUID digitalSkyServiceProviderId,
    @Parameter(
      name = "DigitalSkyServiceProvider",
      description = "Create a new digitalSkyServiceProvider in the store",
      required = true
    ) @Valid @RequestBody DigitalSkyServiceProvider digitalSkyServiceProvider
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
