/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.ispirt.pushpaka.registry.api;

import in.ispirt.pushpaka.models.Manufacturer;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

@Generated(
  value = "org.openapitools.codegen.languages.SpringCodegen",
  date = "2023-09-07T22:13:29.143496+05:30[Asia/Kolkata]"
)
@Validated
@Tag(name = "manufacturers", description = "Manufacturers")
public interface ManufacturerApi {
  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  @Operation(
    operationId = "addManufacturer",
    summary = "Add a new manufacturer to the store",
    description = "Add a new manufacturer to the store",
    tags = { "manufacturer" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Manufacturer.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/manufacturer",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<Manufacturer> addManufacturer(
    @Parameter(
      name = "Manufacturer",
      description = "Create a new manufacturer in the store",
      required = true
    ) @Valid @RequestBody Manufacturer manufacturer
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "deleteManufacturer",
    summary = "Deletes a manufacturer",
    description = "",
    tags = { "manufacturer" },
    responses = {
      @ApiResponse(responseCode = "400", description = "Invalid manufacturer value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.DELETE, value = "/manufacturer/{manufacturerId}")
  default ResponseEntity<Void> deleteManufacturer(
    @Parameter(
      name = "manufacturerId",
      description = "Manufacturer id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("manufacturerId") UUID manufacturerId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "findManufacturers",
    summary = "Finds Manufacturers",
    tags = { "manufacturer" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            array = @ArraySchema(schema = @Schema(implementation = Manufacturer.class))
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/manufacturer/find",
    produces = { "application/json" }
  )
  default ResponseEntity<List<Manufacturer>> findManufacturers() {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "getManufacturerById",
    summary = "Find manufacturer by ID",
    description = "Returns a single manufacturer",
    tags = { "manufacturer" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Manufacturer.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "Manufacturer not found")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/manufacturer/{manufacturerId}",
    produces = { "application/json" }
  )
  default ResponseEntity<Manufacturer> getManufacturerById(
    @Parameter(
      name = "manufacturerId",
      description = "ID of manufacturer to return",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("manufacturerId") UUID manufacturerId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "updateManufacturer",
    summary = "Updates a manufacturer in the store",
    description = "",
    tags = { "manufacturer" },
    responses = { @ApiResponse(responseCode = "405", description = "Invalid input") },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.PUT, value = "/manufacturer/{manufacturerId}")
  default ResponseEntity<Manufacturer> updateManufacturer(
    @Parameter(
      name = "manufacturerId",
      description = "ID of manufacturer that needs to be updated",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("manufacturerId") UUID manufacturerId,
    @Parameter(
      name = "Manufacturer",
      description = "Create a new manufacturer in the store",
      required = true
    ) @Valid @RequestBody Manufacturer manufacturer
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
