/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.ispirt.pushpaka.registry.api;

import in.ispirt.pushpaka.models.Operator;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

@Generated(
  value = "org.openapitools.codegen.languages.SpringCodegen",
  date = "2023-09-07T22:13:29.143496+05:30[Asia/Kolkata]"
)
@Validated
@Tag(name = "operators", description = "Operators")
public interface OperatorApi {
  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  @Operation(
    operationId = "addOperator",
    summary = "Add a new operator to the store",
    description = "Add a new operator to the store",
    tags = { "operator" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Operator.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/operator",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<Operator> addOperator(
    @Parameter(
      name = "Operator",
      description = "Create a new operator in the store",
      required = true
    ) @Valid @RequestBody Operator operator
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "deleteOperator",
    summary = "Deletes a operator",
    description = "",
    tags = { "operator" },
    responses = {
      @ApiResponse(responseCode = "400", description = "Invalid operator value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.DELETE, value = "/operator/{operatorId}")
  default ResponseEntity<Void> deleteOperator(
    @Parameter(
      name = "operatorId",
      description = "Operator id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("operatorId") UUID operatorId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "findOperators",
    summary = "Finds Operators",
    tags = { "operator" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            array = @ArraySchema(schema = @Schema(implementation = Operator.class))
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/operator/find",
    produces = { "application/json" }
  )
  default ResponseEntity<List<Operator>> findOperators() {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "getOperatorById",
    summary = "Find operator by ID",
    description = "Returns a single operator",
    tags = { "operator" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Operator.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "Operator not found")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/operator/{operatorId}",
    produces = { "application/json" }
  )
  default ResponseEntity<Operator> getOperatorById(
    @Parameter(
      name = "operatorId",
      description = "ID of operator to return",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("operatorId") UUID operatorId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "updateOperator",
    summary = "Updates a operator in the store",
    description = "",
    tags = { "operator" },
    responses = { @ApiResponse(responseCode = "405", description = "Invalid input") },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.PUT, value = "/operator/{operatorId}")
  default ResponseEntity<Operator> updateOperator(
    @Parameter(
      name = "operatorId",
      description = "ID of operator that needs to be updated",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("operatorId") UUID operatorId,
    @Parameter(
      name = "Operator",
      description = "Create a new operator in the store",
      required = true
    ) @Valid @RequestBody Operator operator
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
