/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.ispirt.pushpaka.registry.api;

import in.ispirt.pushpaka.models.Lease;
import in.ispirt.pushpaka.models.ModelApiResponse;
import in.ispirt.pushpaka.models.Sale;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

@Generated(
  value = "org.openapitools.codegen.languages.SpringCodegen",
  date = "2023-09-07T22:13:29.143496+05:30[Asia/Kolkata]"
)
@Validated
@Tag(name = "ownership", description = "the ownership API")
public interface OwnershipApi {
  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  /******************************
   *            LEASE           *
   ******************************/

  @Operation(
    operationId = "addLease",
    summary = "Add a new lease to the store",
    description = "Add a new lease to the store",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Lease.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/lease",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<Lease> addLease(
    @Parameter(
      name = "Lease",
      description = "Create a new lease in the store",
      required = true
    ) @Valid @RequestBody Lease lease
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "deleteLease",
    summary = "Deletes a lease",
    description = "",
    responses = {
      @ApiResponse(responseCode = "400", description = "Invalid lease value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.DELETE, value = "/lease/{leaseId}")
  default ResponseEntity<Void> deleteLease(
    @Parameter(
      name = "leaseId",
      description = "Lease id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("leaseId") UUID leaseId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "findLeases",
    summary = "Finds Leases",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            array = @ArraySchema(schema = @Schema(implementation = Lease.class))
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/lease/find",
    produces = { "application/json" }
  )
  default ResponseEntity<List<Lease>> findLeases() {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "getLeaseById",
    summary = "Find lease by ID",
    description = "Returns a single lease",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Lease.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "Lease not found")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/lease/{leaseId}",
    produces = { "application/json" }
  )
  default ResponseEntity<Lease> getLeaseById(
    @Parameter(
      name = "leaseId",
      description = "ID of lease to return",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("leaseId") UUID leaseId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "updateLease",
    summary = "Update an existing lease",
    description = "Update an existing lease by Id",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Lease.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "Lease not found"),
      @ApiResponse(responseCode = "405", description = "Validation exception")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.PUT,
    value = "/lease",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<Lease> updateLease(
    @Parameter(
      name = "Lease",
      description = "Update an existent lease in the store",
      required = true
    ) @Valid @RequestBody Lease lease
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /******************************
   *             SALE           *
   ******************************/

  @Operation(
    operationId = "addSale",
    summary = "Add a new sale to the store",
    description = "Add a new sale to the store",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Sale.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/sale",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<Sale> addSale(
    @Parameter(
      name = "Sale",
      description = "Create a new sale in the store",
      required = true
    ) @Valid @RequestBody Sale sale
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "deleteSale",
    summary = "Deletes a sale",
    description = "",
    responses = {
      @ApiResponse(responseCode = "400", description = "Invalid sale value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.DELETE, value = "/sale/{saleId}")
  default ResponseEntity<Void> deleteSale(
    @Parameter(
      name = "saleId",
      description = "Sale id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("saleId") UUID saleId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "findSales",
    summary = "Finds Sales",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            array = @ArraySchema(schema = @Schema(implementation = Sale.class))
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/sale/find/{uasId}",
    produces = { "application/json" }
  )
  default ResponseEntity<List<Sale>> findSales(
    @Parameter(
      name = "uasId",
      description = "Uas id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("uasId") UUID uasId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "getSaleById",
    summary = "Find sale by ID",
    description = "Returns a single sale",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Sale.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "Sale not found")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/sale/{saleId}",
    produces = { "application/json" }
  )
  default ResponseEntity<Sale> getSaleById(
    @Parameter(
      name = "saleId",
      description = "ID of sale to return",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("saleId") UUID saleId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "updateSale",
    summary = "Update an existing sale",
    description = "Update an existing sale by Id",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Sale.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "Sale not found"),
      @ApiResponse(responseCode = "405", description = "Validation exception")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.PUT,
    value = "/sale",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<Sale> updateSale(
    @Parameter(
      name = "Sale",
      description = "Update an existent sale in the store",
      required = true
    ) @Valid @RequestBody Sale sale
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
