/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.ispirt.pushpaka.registry.api;

import in.ispirt.pushpaka.models.Pilot;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

@Generated(
  value = "org.openapitools.codegen.languages.SpringCodegen",
  date = "2023-09-07T22:13:29.143496+05:30[Asia/Kolkata]"
)
@Validated
@Tag(name = "pilot", description = "Pilots")
public interface PilotApi {
  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  @Operation(
    operationId = "addPilot",
    summary = "Add a new pilot to the store",
    description = "Add a new pilot to the store",
    tags = { "pilot" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Pilot.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/pilot",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<Pilot> addPilot(
    @Parameter(
      name = "Pilot",
      description = "Create a new pilot in the store",
      required = true
    ) @Valid @RequestBody Pilot pilot
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "deletePilot",
    summary = "Deletes a pilot",
    description = "",
    tags = { "pilot" },
    responses = {
      @ApiResponse(responseCode = "400", description = "Invalid pilot value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.DELETE, value = "/pilot/{pilotId}")
  default ResponseEntity<Void> deletePilot(
    @Parameter(
      name = "pilotId",
      description = "Pilot id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("pilotId") UUID pilotId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "findPilots",
    summary = "Finds Pilots",
    tags = { "pilot" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            array = @ArraySchema(schema = @Schema(implementation = Pilot.class))
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/pilot/find",
    produces = { "application/json" }
  )
  default ResponseEntity<List<Pilot>> findPilots() {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "getPilotById",
    summary = "Find pilot by ID",
    description = "Returns a single pilot",
    tags = { "pilot" },
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Pilot.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "Pilot not found")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/pilot/{pilotId}",
    produces = { "application/json" }
  )
  default ResponseEntity<Pilot> getPilotById(
    @Parameter(
      name = "pilotId",
      description = "ID of pilot to return",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("pilotId") UUID pilotId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "updatePilot",
    summary = "Updates a pilot in the store",
    description = "",
    tags = { "pilot" },
    responses = { @ApiResponse(responseCode = "405", description = "Invalid input") },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.PUT, value = "/pilot/{pilotId}")
  default ResponseEntity<Pilot> updatePilot(
    @Parameter(
      name = "pilotId",
      description = "ID of pilot that needs to be updated",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("pilotId") UUID pilotId,
    @Parameter(
      name = "Pilot",
      description = "Create a new pilot in the store",
      required = true
    ) @Valid @RequestBody Pilot pilot
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
