/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.ispirt.pushpaka.registry.api;

import in.ispirt.pushpaka.models.Trader;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

@Generated(
  value = "org.openapitools.codegen.languages.SpringCodegen",
  date = "2023-09-07T22:13:29.143496+05:30[Asia/Kolkata]"
)
@Validated
@Tag(name = "traders", description = "Traders")
public interface TraderApi {
  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  @Operation(
    operationId = "addTrader",
    summary = "Add a new trader to the store",
    description = "Add a new trader to the store",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Trader.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/trader",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<Trader> addTrader(
    @Parameter(
      name = "Trader",
      description = "Create a new trader in the store",
      required = true
    ) @Valid @RequestBody Trader trader
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "deleteTrader",
    summary = "Deletes a trader",
    description = "",
    responses = {
      @ApiResponse(responseCode = "400", description = "Invalid trader value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.DELETE, value = "/trader/{traderId}")
  default ResponseEntity<Void> deleteTrader(
    @Parameter(
      name = "traderId",
      description = "Trader id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("traderId") UUID traderId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "findTraders",
    summary = "Finds Traders",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            array = @ArraySchema(schema = @Schema(implementation = Trader.class))
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/trader/find",
    produces = { "application/json" }
  )
  default ResponseEntity<List<Trader>> findTraders() {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "getTraderById",
    summary = "Find trader by ID",
    description = "Returns a single trader",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = Trader.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "Trader not found")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/trader/{traderId}",
    produces = { "application/json" }
  )
  default ResponseEntity<Trader> getTraderById(
    @Parameter(
      name = "traderId",
      description = "ID of trader to return",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("traderId") UUID traderId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "updateTrader",
    summary = "Updates a trader in the store",
    description = "",
    responses = { @ApiResponse(responseCode = "405", description = "Invalid input") },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.PUT, value = "/trader/{traderId}")
  default ResponseEntity<Trader> updateTrader(
    @Parameter(
      name = "traderId",
      description = "ID of trader that needs to be updated",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("traderId") UUID traderId,
    @Parameter(
      name = "Trader",
      description = "Create a new trader in the store",
      required = true
    ) @Valid @RequestBody Trader trader
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
