/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.ispirt.pushpaka.registry.api;

import in.ispirt.pushpaka.models.UasType;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import javax.annotation.Generated;
import javax.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

@Generated(
  value = "org.openapitools.codegen.languages.SpringCodegen",
  date = "2023-09-07T22:13:29.143496+05:30[Asia/Kolkata]"
)
@Validated
@Tag(name = "uasTypes", description = "the uas_types API")
public interface UasTypeApi {
  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  @Operation(
    operationId = "approveUasType",
    summary = "Approve a new uasType to the store",
    description = "Approve a new uasType to the store",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = UasType.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/uasType/approve/{uasTypeId}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<UasType> approveUasType(
    @Parameter(
      name = "model_number",
      description = "Model Number assigned to new uasType in the store",
      required = true
    ) @Valid @RequestBody Integer modelNumber,
    @Parameter(
      name = "uas_type_id",
      description = "UasType ID for the new uasType in the store",
      required = true
    ) @PathVariable("uasTypeId") UUID uasTypeId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "addUasType",
    summary = "Add a new uasType to the store",
    description = "Add a new uasType to the store",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = UasType.class)
          )
        }
      ),
      @ApiResponse(responseCode = "405", description = "Invalid input")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.POST,
    value = "/uasType",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<UasType> addUasType(
    @Parameter(
      name = "UasType",
      description = "Create a new uasType in the store",
      required = true
    ) @Valid @RequestBody UasType uasType
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "deleteUasType",
    summary = "Deletes a uasType",
    description = "",
    responses = {
      @ApiResponse(responseCode = "400", description = "Invalid uasType value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(method = RequestMethod.DELETE, value = "/uasType/{uasTypeId}")
  default ResponseEntity<Void> deleteUasType(
    @Parameter(
      name = "uasTypeId",
      description = "UasType id to delete",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("uasTypeId") UUID uasTypeId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "findUasTypes",
    summary = "Finds UasTypes",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            array = @ArraySchema(schema = @Schema(implementation = UasType.class))
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid value")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/uasType/find",
    produces = { "application/json" }
  )
  default ResponseEntity<List<UasType>> findUasTypes() {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "getUasTypeById",
    summary = "Find uasType by ID",
    description = "Returns a single uasType",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = UasType.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "UasType not found")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.GET,
    value = "/uasType/{uasTypeId}",
    produces = { "application/json" }
  )
  default ResponseEntity<UasType> getUasTypeById(
    @Parameter(
      name = "uasTypeId",
      description = "ID of uasType to return",
      required = true,
      in = ParameterIn.PATH
    ) @PathVariable("uasTypeId") UUID uasTypeId
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  @Operation(
    operationId = "updateUasType",
    summary = "Update an existing uasType",
    description = "Update an existing uasType by Id",
    responses = {
      @ApiResponse(
        responseCode = "200",
        description = "Successful operation",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = UasType.class)
          )
        }
      ),
      @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
      @ApiResponse(responseCode = "404", description = "UasType not found"),
      @ApiResponse(responseCode = "405", description = "Validation exception")
    },
    security = { @SecurityRequirement(name = "jwt") }
  )
  @RequestMapping(
    method = RequestMethod.PUT,
    value = "/uasType",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  default ResponseEntity<UasType> updateUasType(
    @Parameter(
      name = "UasType",
      description = "Update an existent uasType in the store",
      required = true
    ) @Valid @RequestBody UasType uasType
  ) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
