@startuml
!include ../common.puml

Manufacturer -> Registry : Create Application Request
Registry -> Manufacturer : Create Application Response

loop till application approved

loop while application needs changes

Manufacturer -> Registry : Update Application Request
Registry -> Manufacturer : Update Application Response
end

Manufacturer -> Registry : Submit Application Request
Registry -> Manufacturer : Submit Application Response

actor Administrator

Registry -> Administrator : Application Approval Request
Administrator -> Registry : Application Approval Response
Registry -> Manufacturer : Application Approval Status Notification

end

@enduml
``