@startuml
!include ../common.puml

Manufacturer -> Registry : UasType Deregistration Request
Registry -> Manufacturer : UasType Deregistration Response
actor Administrator
Registry -> Administrator : Application Approval Request
Administrator -> Registry : Application Approval Response
Registry -> Manufacturer : Application Approval Status Notification
@enduml
